export const addonsTypes = {
  ADDON_LIST_REQUEST: 'ADDON_LIST_REQUEST',
  ADDON_LIST_SUCCESS: 'ADDON_LIST_SUCCESS',
  ADDON_LIST_FAIL: 'ADDON_LIST_FAIL',

  ADDON_CREATE_REQUEST: 'ADDON_CREATE_REQUEST',
  ADDON_CREATE_SUCCESS: 'ADDON_CREATE_SUCCESS',
  ADDON_CREATE_FAIL: 'ADDON_CREATE_FAIL',
  ADDON_CREATE_RESET: 'ADDON_CREATE_RESET',

  ADDON_FIND_REQUEST: 'ADDON_FIND_REQUEST',
  ADDON_FIND_SUCCESS: 'ADDON_FIND_SUCCESS',
  ADDON_FIND_FAIL: 'ADDON_FIND_FAIL',
  ADDON_FIND_RESET: 'ADDON_FIND_RESET',

  ADDON_UPDATE_REQUEST: 'ADDON_UPDATE_REQUEST',
  ADDON_UPDATE_SUCCESS: 'ADDON_UPDATE_SUCCESS',
  ADDON_UPDATE_FAIL: 'ADDON_UPDATE_FAIL',
  ADDON_UPDATE_RESET: 'ADDON_UPDATE_RESET',
};
