export const addonCategoryTypes = {
    ADDON_CATEGORY_LIST_REQUEST: 'ADDON_CATEGORY_LIST_REQUEST',
    ADDON_CATEGORY_LIST_SUCCESS: 'ADDON_CATEGORY_LIST_SUCCESS',
    ADDON_CATEGORY_LIST_FAIL: 'ADDON_CATEGORY_LIST_FAIL',
}

