export const addonCategoryTypes = {
  ADDON_CATEGORY_LIST_REQUEST: 'ADDON_CATEGORY_LIST_REQUEST',
  ADDON_CATEGORY_LIST_SUCCESS: 'ADDON_CATEGORY_LIST_SUCCESS',
  ADDON_CATEGORY_LIST_FAIL: 'ADDON_CATEGORY_LIST_FAIL',

  ADDON_CATEGORY_DETAILS_REQUEST: 'ADDON_CATEGORY_DETAILS_REQUEST',
  ADDON_CATEGORY_DETAILS_SUCCESS: 'ADDON_CATEGORY_DETAILS_SUCCESS',
  ADDON_CATEGORY_DETAILS_FAIL: 'ADDON_CATEGORY_DETAILS_FAIL',
  ADDON_CATEGORY_DETAILS_RESET: 'ADDON_CATEGORY_DETAILS_RESET',

  ADDON_CATEGORY_UPDATE_REQUEST: 'ADDON_CATEGORY_UPDATE_REQUEST',
  ADDON_CATEGORY_UPDATE_SUCCESS: 'ADDON_CATEGORY_UPDATE_SUCCESS',
  ADDON_CATEGORY_UPDATE_FAIL: 'ADDON_CATEGORY_UPDATE_FAIL',
  ADDON_CATEGORY_UPDATE_RESET: 'ADDON_CATEGORY_UPDATE_RESET',

  ADDON_CATEGORY_CREATE_REQUEST: 'ADDON_CATEGORY_CREATE_REQUEST',
  ADDON_CATEGORY_CREATE_SUCCESS: 'ADDON_CATEGORY_CREATE_SUCCESS',
  ADDON_CATEGORY_CREATE_FAIL: 'ADDON_CATEGORY_CREATE_FAIL',
  ADDON_CATEGORY_CREATE_RESET: 'ADDON_CATEGORY_CREATE_RESET'
};
