export const addonsTypes = {
    ADDON_LIST_REQUEST : 'ADDON_LIST_REQUEST',
    ADDON_LIST_SUCCESS : 'ADDON_LIST_SUCCESS',
    ADDON_LIST_FAIL : 'ADDON_LIST_FAIL',
    
    ADDON_CREATE_REQUEST : 'ADDON_CREATE_REQUEST',
    ADDON_CREATE_SUCCESS : 'ADDON_CREATE_SUCCESS',
    ADDON_CREATE_FAIL : 'ADDON_CREATE_FAIL',
}

