export const addonCategoriesTypes = {
  ADDON_CATEGORIES_LIST_REQUEST: 'ADDON_CATEGORIES_LIST_REQUEST',
  ADDON_CATEGORIES_LIST_SUCCESS: 'ADDON_CATEGORIES_LIST_SUCCESS',
  ADDON_CATEGORIES_LIST_FAIL: 'ADDON_CATEGORIES_LIST_FAIL',
};
