export const addressesTypes = {
    SUPPORTED_COUNTRIES_REQUEST: 'SUPPORTED_COUNTRIES_REQUEST',
    SUPPORTED_COUNTRIES_SUCCESS: 'SUPPORTED_COUNTRIES_SUCCESS',
    SUPPORTED_COUNTRIES_FAIL: 'SUPPORTED_COUNTRIES_FAIL'
}