export const couponsTypes = {
  COUPON_LIST_REQUEST: 'COUPON_LIST_REQUEST',
  COUPON_LIST_SUCCESS: 'COUPON_LIST_SUCCESS',
  COUPON_LIST_FAIL: 'COUPON_LIST_FAIL',

  COUPON_CREATE_REQUEST: 'COUPON_CREATE_REQUEST',
  COUPON_CREATE_SUCCESS: 'COUPON_CREATE_SUCCESS',
  COUPON_CREATE_FAIL: 'COUPON_CREATE_FAIL',
  COUPON_CREATE_RESET: 'COUPON_CREATE_RESET',

  COUPON_FIND_REQUEST: 'COUPON_FIND_REQUEST',
  COUPON_FIND_SUCCESS: 'COUPON_FIND_SUCCESS',
  COUPON_FIND_FAIL: 'COUPON_FIND_FAIL',
  COUPON_FIND_RESET: 'COUPON_FIND_RESET',

  COUPON_UPDATE_REQUEST: 'COUPON_UPDATE_REQUEST',
  COUPON_UPDATE_SUCCESS: 'COUPON_UPDATE_SUCCESS',
  COUPON_UPDATE_FAIL: 'COUPON_UPDATE_FAIL',
  COUPON_UPDATE_RESET: 'COUPON_UPDATE_RESET',
};
