export const couponsTypes = {
  COUPON_LIST_REQUEST: 'COUPON_LIST_REQUEST',
  COUPON_LIST_SUCCESS: 'COUPON_LIST_SUCCESS',
  COUPON_LIST_FAIL: 'COUPON_LIST_FAIL',

  COUPON_CREATE_REQUEST: 'COUPON_CREATE_REQUEST',
  COUPON_CREATE_SUCCESS: 'COUPON_CREATE_SUCCESS',
  COUPON_CREATE_FAIL: 'COUPON_CREATE_FAIL',
  COUPON_CREATE_RESET: 'COUPON_CREATE_RESET',
};
