export const dashboardTypes = {

    DAILY_ORDERS_LIST_REQUEST : 'DAILY_ORDERS_LIST_REQUEST',
    DAILY_ORDERS_LIST_SUCCESS : 'DAILY_ORDERS_LIST_SUCCESS',
    DAILY_ORDERS_LIST_FAIL : 'DAILY_ORDERS_LIST_FAIL',
}