export const dashboardTypes = {

    DASHBOARD_REPORT_LIST_REQUEST : 'DASHBOARD_REPORT_LIST_REQUEST',
    DASHBOARD_REPORT_LIST_SUCCESS : 'DASHBOARD_REPORT_LIST_SUCCESS',
    DASHBOARD_REPORT_LIST_FAIL : 'DASHBOARD_REPORT_LIST_FAIL',
}