export const deliveriesTypes = {
  DELIVERY_LIST_REQUEST : 'DELIVERY_LIST_REQUEST',
  DELIVERY_LIST_SUCCESS : 'DELIVERY_LIST_SUCCESS',
  DELIVERY_LIST_UPDATE: 'DELIVERY_LIST_UPDATE',
  DELIVERY_LIST_FAIL : 'DELIVERY_LIST_FAIL',
}

