export const deliveriesTypes = {
  DELIVERY_LIST_REQUEST : 'DELIVERY_LIST_REQUEST',
  DELIVERY_LIST_SUCCESS : 'DELIVERY_LIST_SUCCESS',
  DELIVERY_LIST_FAIL : 'DELIVERY_LIST_FAIL',
  DELIVERY_LIST_RESET: 'DELIVERY_LIST_RESET',

  
  DELIVERY_LIST_DETAILS_REQUEST : 'DELIVERY_LIST_DETAILS_REQUEST',
  DELIVERY_LIST_DETAILS_SUCCESS : 'DELIVERY_LIST_DETAILS_SUCCESS',
  DELIVERY_LIST_DETAILS_FAIL : 'DELIVERY_LIST_DETAILS_FAIL',
  DELIVERY_LIST_DETAILS_RESET: 'DELIVERY_LIST_DETAILS_RESET',
}

