export const foodCategoryTypes = {
    FOOD_CATEGORY_LIST_REQUEST : 'FOOD_CATEGORY_LIST_REQUEST',
    FOOD_CATEGORY_LIST_SUCCESS : 'FOOD_CATEGORY_LIST_SUCCESS',
    FOOD_CATEGORY_LIST_FAIL : 'FOOD_CATEGORY_LIST_FAIL',

    FOOD_CATEGORY_DETAILS_REQUEST: 'FOOD_CATEGORY_DETAILS_REQUEST',
    FOOD_CATEGORY_DETAILS_SUCCESS: 'FOOD_CATEGORY_DETAILS_SUCCESS',
    FOOD_CATEGORY_DETAILS_FAIL: 'FOOD_CATEGORY_DETAILS_FAIL',
    
    FOOD_CATEGORY_CREATE_REQUEST: 'FOOD_CATEGORY_CREATE_REQUEST',
    FOOD_CATEGORY_CREATE_SUCCESS: 'FOOD_CATEGORY_CREATE_SUCCESS',
    FOOD_CATEGORY_CREATE_FAIL: 'FOOD_CATEGORY_CREATE_FAIL',
    FOOD_CATEGORY_CREATE_RESET: 'FOOD_CATEGORY_CREATE_RESET',
}

