export const foodsTypes = {
    FOOD_CREATE_REQUEST : 'FOOD_CREATE_REQUEST',
    FOOD_CREATE_SUCCESS : 'FOOD_CREATE_SUCCESS',
    FOOD_CREATE_FAIL : 'FOOD_CREATE_FAIL',

    FOOD_UPDATE_REQUEST : 'FOOD_UPDATE_REQUEST',
    FOOD_UPDATE_SUCCESS : 'FOOD_UPDATE_SUCCESS',
    FOOD_UPDATE_FAIL : 'FOOD_UPDATE_FAIL',
    
    FOOD_FIND_REQUEST : 'FOOD_FIND_REQUEST',
    FOOD_FIND_SUCCESS : 'FOOD_FIND_SUCCESS',
    FOOD_FIND_FAIL : 'FOOD_FIND_FAIL',
}

