export const foodCategoryTypes = {
    FOOD_CATEGORY_LIST_REQUEST : 'FOOD_CATEGORY_LIST_REQUEST',
    FOOD_CATEGORY_LIST_SUCCESS : 'FOOD_CATEGORY_LIST_SUCCESS',
    FOOD_CATEGORY_LIST_FAIL : 'FOOD_CATEGORY_LIST_FAIL',
}

