export const ordersTypes = {
    ORDER_LIST_REQUEST : 'ORDER_LIST_REQUEST',
    ORDER_LIST_SUCCESS : 'ORDER_LIST_SUCCESS',
    ORDER_LIST_UPDATE: 'ORDER_LIST_UPDATE',
    ORDER_LIST_FAIL : 'ORDER_LIST_FAIL',

    ORDER_FIND_REQUEST : 'ORDER_FIND_REQUEST',
    ORDER_FIND_SUCCESS : 'ORDER_FIND_SUCCESS',
    ORDER_FIND_FAIL : 'ORDER_FIND_FAIL',
}

