export const ordersTypes = {
    ORDER_LIST_REQUEST : 'ORDER_LIST_REQUEST',
    ORDER_LIST_SUCCESS : 'ORDER_LIST_SUCCESS',
    ORDER_LIST_UPDATE: 'ORDER_LIST_UPDATE',
    ORDER_LIST_FAIL : 'ORDER_LIST_FAIL',

    FETCH_ORDER_FROM_STORE : 'FETCH_ORDER_FROM_STORE',

}

