export const ordersTypes = {
    ORDER_LIST_REQUEST : 'ORDER_LIST_REQUEST',
    ORDER_LIST_SUCCESS : 'ORDER_LIST_SUCCESS',
    ORDER_LIST_UPDATE: 'ORDER_LIST_UPDATE',
    ORDER_LIST_FAIL : 'ORDER_LIST_FAIL',

    FIND_ORDER_REQUEST : 'FIND_ORDER_REQUEST',
    FIND_ORDER_SUCCESS: 'FIND_ORDER_SUCCESS',
    FIND_ORDER_FAIL: 'FIND_ORDER_FAIL'

}

