export const paymentsTypes = {

    UNTRANSFERED_PAYMENTS_REQUEST: 'UNTRANSFERED_PAYMENTS_REQUEST',
    UNTRANSFERED_PAYMENTS_SUCCESS: 'UNTRANSFERED_PAYMENTS_SUCCESS',
    UNTRANSFERED_PAYMENTS_FAIL: 'UNTRANSFERED_PAYMENTS_FAIL'
}