export const restaurantsTypes = {
    GET_ALL_RESTAURANTS:"GET_ALL_RESTAURANTS",

    RESTAURAT_OWNER_LIST_REQUEST : 'RESTAURAT_OWNER_LIST_REQUEST',
    RESTAURAT_OWNER_LIST_SUCCESS : 'RESTAURAT_OWNER_LIST_SUCCESS',
    RESTAURAT_OWNER_LIST_FAIL : 'RESTAURAT_OWNER_LIST_FAIL',

    RESTAURAT_UPDATE_REQUEST : 'RESTAURAT_UPDATE_REQUEST',
    RESTAURAT_UPDATE_SUCCESS : 'RESTAURAT_UPDATE_SUCCESS',
    RESTAURAT_UPDATE_FAIL : 'RESTAURAT_UPDATE_FAIL',

    RESTAURAT_LIST_REQUEST : 'RESTAURAT_LIST_REQUEST',
    RESTAURAT_LIST_SUCCESS : 'RESTAURAT_LIST_SUCCESS',
    RESTAURAT_LIST_FAIL : 'RESTAURAT_LIST_FAIL',

    RESTAURAT_FIND_REQUEST : 'RESTAURAT_FIND_REQUEST',
    RESTAURAT_FIND_SUCCESS : 'RESTAURAT_FIND_SUCCESS',
    RESTAURAT_FIND_FAIL : 'RESTAURAT_FIND_FAIL',


    
}