export const sendNotificationTypes = {
  NOTIFICATION_CREATE_REQUEST: 'NOTIFICATION_CREATE_REQUEST',
  NOTIFICATION_CREATE_SUCCESS: 'NOTIFICATION_CREATE_SUCCESS',
  NOTIFICATION_CREATE_FAIL: 'NOTIFICATION_CREATE_FAIL',
  NOTIFICATION_CREATE_RESET: 'NOTIFICATION_CREATE_RESET',

  SEND_NOTIFICATION_REQUEST: 'SEND_NOTIFICATION_REQUEST',
  SEND_NOTIFICATION_SUCCESS: 'SEND_NOTIFICATION_SUCCESS',
  SEND_NOTIFICATION_FAIL: 'SEND_NOTIFICATION_FAIL',
};
