export const sendNotificationTypes = {
  SEND_NOTIFICATION_REQUEST: 'SEND_NOTIFICATION_REQUEST',
  SEND_NOTIFICATION_SUCCESS: 'SEND_NOTIFICATION_SUCCESS',
  SEND_NOTIFICATION_FAIL: 'SEND_NOTIFICATION_FAIL',
};
