export const settingsTypes = {
  SETTINGS_LIST_REQUEST: 'SETTINGS_LIST_REQUEST',
  SETTINGS_LIST_SUCCESS: 'SETTINGS_LIST_SUCCESS',
  SETTINGS_LIST_FAIL: 'SETTINGS_LIST_FAIL',

  SETTINGS_UPDATE_REQUEST: 'SETTINGS_UPDATE_REQUEST',
  SETTINGS_UPDATE_SUCCESS: 'SETTINGS_UPDATE_SUCCESS',
  SETTINGS_UPDATE_FAIL: 'SETTINGS_UPDATE_FAIL',
  SETTINGS_UPDATE_RESET: 'SETTINGS_UPDATE_RESET',
};
