export const settingsTypes = {
  SETTINGS_LIST_REQUEST: 'SETTINGS_LIST_REQUEST',
  SETTINGS_LIST_SUCCESS: 'SETTINGS_LIST_SUCCESS',
  SETTINGS_LIST_FAIL: 'SETTINGS_LIST_FAIL',

  SETTINGS_UPDATE_REQUEST: 'SETTINGS_UPDATE_REQUEST',
  SETTINGS_UPDATE_SUCCESS: 'SETTINGS_UPDATE_SUCCESS',
  SETTINGS_UPDATE_FAIL: 'SETTINGS_UPDATE_FAIL',
  SETTINGS_UPDATE_RESET: 'SETTINGS_UPDATE_RESET',

  SETTINGS_FORGOT_PASSWORD_REQUEST:"SETTINGS_FORGOT_PASSWORD_REQUEST",
  SETTINGS_FORGOT_PASSWORD_SUCCESS:"SETTINGS_FORGOT_PASSWORD_SUCCESS",
  SETTINGS_FORGOT_PASSWORD_FAIL:"SETTINGS_FORGOT_PASSWORD_FAIL",

  SETTINGS_SCHEDULE_UPDATE_REQUEST:"SETTINGS_SCHEDULE_UPDATE_REQUEST",
  SETTINGS_SCHEDULE_UPDATE_SUCCESS:"SETTINGS_SCHEDULE_UPDATE_SUCCESS",
  SETTINGS_SCHEDULE_UPDATE_FAIL:"SETTINGS_SCHEDULE_UPDATE_FAIL"
};
