export const userTypes = {
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',

  RESET_PASSWORD_REQUEST_REQUEST: 'RESET_PASSWORD_REQUEST_REQUEST',
  RESET_PASSWORD_REQUEST_SUCCESS: 'RESET_PASSWORD_REQUEST_SUCCESS',
  RESET_PASSWORD_REQUEST_FAIL: 'RESET_PASSWORD_REQUEST_FAIL',
  RESET_PASSWORD_REQUEST_RESET: 'RESET_PASSWORD_REQUEST_RESET',
};
