export const usersListTypes = {

    CUSTOMER_LIST_REQUEST : 'CUSTOMER_LIST_REQUEST',
    CUSTOMER_LIST_SUCCESS : 'CUSTOMER_LIST_SUCCESS',
    CUSTOMER_LIST_FAIL : 'CUSTOMER_LIST_FAIL',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAIL: 'GET_USER_FAIL',

    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    UPDATE_USER_END: 'UPDATE_USER_END'
}