export const userTypes = {
    LOGIN:"LOGIN",
    LOGIN_FAILED:"LOGIN_FAILED",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",

    CHANGE_PASSWORD_REQUEST:"CHANGE_PASSWORD_REQUEST",
    CHANGE_PASSWORD_SUCCESS:"CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_FAILED:"CHANGE_PASSWORD_FAILED",
}