name: Baklava Production Build & Deploy

on:
  push:
    branches: [V-0.1.15]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Create Env File
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NODE_ENV: "production"
          envkey_NEXT_PUBLIC_GOOGLE_FCM_AUTH_KEY: ${{ secrets.DEV_GOOGLE_FCM_AUTH_KEY }}
          envkey_NEXT_PUBLIC_API_URL: "https://api.eve-yemek.com"
          envkey_NEXT_PUBLIC_API_MODE: "production"
          envkey_NEXT_PUBLIC_HOTJAR_TRACKING_ID: ${{ secrets.PROD_HOTJAR_TRACKING_ID }}
          file_name: .env
      - name: Copy ENV To Box
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: root
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          source: "./.env"
          target: "/srv/baklava/"
      - name: Box Box Box!
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: root
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            cd /srv/baklava/
            git restore .
            git fetch
            git checkout V-0.1.15
            yarn install && yarn build
            pm2 reload baklava --update-env
